dcmfile_path: /data/inference_task/test
save_path : /data/inference_result/wrist_AP_eval

arch:
  classify: MobileNet_v2_onecls
  landmarks: 
    net: GLNet
    local_net: unet_dw

num_classes:
  classify: 2
  AP: 3
  LAT: 5

checkpoints:
  classify_position: model_best_wrist-classify-position.pth.tar
  classify_artifact: model_best_wrist-classify-artifact.pth.tar
  classify_overlap: model_best_wrist-classify-overlap.pth.tar
  landmarks_AP: model_best_wrist-landmarks-AP.pth.tar
  landmarks_LAT: model_best_wrist-landmarks-LAT.pth.tar

input_size:
  classify:
    W: 960
    H: 1920
  landmarks:
    W : 640
    H : 1280